ALTER TABLE IF EXISTS appointments
  ADD COLUMN IF NOT EXISTS checked_in_at TIMESTAMP;

ALTER TABLE IF EXISTS medical_records
  ADD COLUMN IF NOT EXISTS clinical_notes TEXT,
  ADD COLUMN IF NOT EXISTS blood_pressure VARCHAR(32),
  ADD COLUMN IF NOT EXISTS temperature NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS weight NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS height NUMERIC(5,2);

ALTER TABLE IF EXISTS prescription_items
  ADD COLUMN IF NOT EXISTS frequency VARCHAR(255),
  ADD COLUMN IF NOT EXISTS duration_days INTEGER,
  ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
