import type { ComponentProps } from "react";
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  ArrowRight,
  BadgeCheck,
  Bell,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarX,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleHelp,
  ClipboardList,
  ClipboardPlus,
  Clock,
  Download,
  Edit3,
  Eye,
  FileText,
  Filter,
  Globe2,
  Info,
  Languages,
  ListOrdered,
  Lock,
  LogIn,
  Mail,
  MapPin,
  MessageCircle,
  Microscope,
  Moon,
  Package,
  Phone,
  Pill,
  Plus,
  PlusCircle,
  Printer,
  ReceiptText,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  ShieldPlus,
  Siren,
  Stethoscope,
  Sun,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  UserPlus,
  UserRound,
  Users,
  WalletCards,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import { cn } from "@/lib/utils";

type HcIconProps = Omit<ComponentProps<"svg">, "name"> & {
  name?: string;
};

const iconMap: Record<string, LucideIcon> = {
  account_circle: UserRound,
  add: Plus,
  add_circle: PlusCircle,
  analytics: Activity,
  apartment: Building2,
  arrow_forward: ArrowRight,
  arrow_forward_ios: ChevronRight,
  assignment: ClipboardList,
  biotech: Microscope,
  bolt: Zap,
  calendar_month: Calendar,
  calendar_today: CalendarDays,
  call: Phone,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  clinical_notes: ClipboardPlus,
  close: X,
  comment: MessageCircle,
  dark_mode: Moon,
  delete: Trash2,
  description: FileText,
  download: Download,
  edit: Edit3,
  edit_note: Edit3,
  emergency: Siren,
  event_busy: CalendarX,
  event_note: CalendarCheck,
  expand_more: ChevronDown,
  filter_list: Filter,
  format_list_numbered: ListOrdered,
  globe: Globe2,
  groups: Users,
  health_metrics: Activity,
  help: CircleHelp,
  help_outline: CircleHelp,
  history: Clock,
  info: Info,
  inventory_2: Package,
  language: Languages,
  location_on: MapPin,
  lock: Lock,
  local_hospital: Stethoscope,
  login: LogIn,
  mail: Mail,
  medical_services: Stethoscope,
  medication: Pill,
  monitoring: Activity,
  monitor_heart: Activity,
  notifications: Bell,
  pending_actions: ClipboardList,
  payments: WalletCards,
  person: UserRound,
  person_add: UserPlus,
  pill: Pill,
  print: Printer,
  priority_high: TriangleAlert,
  radio_button_unchecked: Circle,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  report: FileText,
  schedule: Clock,
  search: Search,
  security: ShieldCheck,
  send: Send,
  settings: Settings,
  share: Share2,
  shield_lock: ShieldCheck,
  sync: RefreshCw,
  timer: Timer,
  trending_up: TrendingUp,
  verified: BadgeCheck,
  verified_user: ShieldPlus,
  visibility: Eye,
  warning: TriangleAlert,
  wb_sunny: Sun,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
};

export function HcIcon({ name = "", className, ...props }: HcIconProps) {
  const Icon = iconMap[name] || CircleHelp;

  return (
    <Icon
      aria-hidden="true"
      className={cn("inline-block size-[1em] shrink-0 align-middle", className)}
      {...props}
    />
  );
}
